### ISSUE TITLE
Colons in {datetime.now()} result in invalid path on Windows

### ISSUE THREAD

**Issue by ThreeDeeJay** [joe-irving/airtable_full_backup#1]
https://github.com/joe-irving/airtable_full_backup/blob/64fc5bba24f22e4831b3c7ee674635dc290b0d3e/airtable_backup.py#L10

```
C:\Programs\airtable_full_backup>airtable_backup.py
Traceback (most recent call last):
  File "C:\Programs\airtable_full_backup\airtable_backup.py", line 12, in <module>
    os.makedirs(backup_dir)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './backups/2023-03-11 00:17:02.026826'
```

**Comment by joe-irving** [comment]
I wrote this to work on Linux as was being lazy! I have now added changed this and pushed to the main branch.
